config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/values'
  get 'pages/howitworks'

  resources :spots do
    get 'top'
  end
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favori.rb
class Favori < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  has_many :favoris
  geocoded_by :adresse
  after_validation :geocode, if: :will_save_change_to_adresse?
  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 40}
  validates :note, presence: true
  validates :adresse, presence: true
  validates :country, presence: true
  validates :meilleure_taille, presence: true
  validates :houle, presence: true
  validates :periode, presence: true
  validates :best_wind, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_adresse,
    against: [ :name, :adresse ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spots
  has_many :favoris
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user
   protect_from_forgery with: :exception

     protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end

  def after_sign_in_path_for(resource)
    spots_path
  end


end

app/controllers/favoris_controller.rb
class FavorisController < ApplicationController
  def index
    @user = current_user
    @favoris = Favori.where(user: @user)
  end

  def create
    @spot = Spot.find(params[:spot_id])
    if @spot.user_id != current_user.id   #You can register favorites other than your own spots
      @favori = Favori.create(user_id: current_user.id, spot_id: @spot.id)
    end
  end

  def destroy
    @favori = Favori.find(params[:id])
    @favori.destroy
    redirect_to user_favoris_path(current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :admin ]

  def home
  end

  def about
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: %i[ show edit update destroy ]

  skip_before_action :verify_authenticity_token

  # GET /spots or /spots.json
  def index

    if params[:query].present?
      @spots = Spot.search_by_name_and_adresse(params[:query])

       @markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        info_window: render_to_string(partial: "info_window", locals: { spot: spot }),
        image_url: helpers.asset_url("vague.png")
      }
    end


    else
    @spots = current_user.spots

    @markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        info_window: render_to_string(partial: "info_window", locals: { spot: spot }),
        image_url: helpers.asset_url("vague.png")
      }
      end
    end
  end

  # GET /spots/1 or /spots/1.json
  def show
        @markers = [{
      lat: @spot.latitude,
      lng: @spot.longitude,
      info_window: render_to_string(partial: "info_window", locals: { spot: @spot }),
      image_url: helpers.asset_url("vague.png")
      }
    ]
  end

  # GET /spots/new
  def new
    if user_signed_in?
      @spot = Spot.new
    else
      redirect_to new_user_registration_path
    end
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots or /spots.json
  def create
    @spot = Spot.new(spot_params)
    @spot.user = current_user

    if @spot.save
      redirect_to spot_path(@spot)
    else
      render :new
    end
  end


  # PATCH/PUT /spots/1 or /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spot_url(@spot), notice: "Ton Spot a bien été mis-à-jour!" }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1 or /spots/1.json
  def destroy
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url, notice: "Le spot a bien été supprimé." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spot_params
      params.require(:spot).permit(:name, :country, :adresse, :publish_date, :best_tide, :best_wind, :latitude, :longitude, :note, :user_id, :description, :image, :periode, :meilleure_taille, :houle )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   skip_before_action :verify_authenticity_token
  def edit
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
    favoris = Favori.where(user_id: current_user.id).order(created_at: :desc).pluck(:post_id)
    @favoris = Post.find(favoris)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favoris/index.html.erb
<h1>Page mes favoris</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareSession</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

       <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
        />
        <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
        <script src="https://api.windy.com/assets/map-forecast/libBoot.js"></script>
        <style>
            #windy {
                width: 100%;
                height: 300px;
            }
        </style>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Palette+Mosaic&family=Roboto:wght@400;700;900&family=Zen+Antique+Soft&display=swap" rel="stylesheet">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/flashes' %>

    <% if user_signed_in? %>
     <%= render 'shared/slidebar' %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>


    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
<div class="values">
  <div class="jumbotron text-center">
    <p style="margin-bottom: 30px; font-size: 20px;">SessionsShare te permets de noter les spots, indiquer la bonne marée, le bon vent. Tu pourras ainsi visualiser sur la map tous tes spots et les partager (si tu le souhaites..) à tes potes.</p>
  </div>

  <!-- Container (About Section) -->
  <div id="about" class="container-fluid">
    <div class="row">
      <div class="col-sm-8">
        <h2>Qui sommes nous ? </h2><br>
        <h4>Un outil open-source, en perpétuelle amélioration.</h4><br>
        <p>Je m'appelle Félix. Développeur à mes heures perdues, j'ai voulu créer un outil pour pouvoir noter mes découvertes. Cet outil n'a pas pour but de rendre libre tous les spots de surf, c'est pourquoi je vous demanderai de ne pas partager vos spots à des inconnus. Faites en bon usage. Aujourd'hui, c'est avec grand plaisir que je vous le partage. </p>
        <br><button style="margin-bottom: 20px;" class="btn btn-success btn-lg">Nous contacter</button>
      </div>
      <div class="col-sm-4">
       <img src="https://images.unsplash.com/photo-1517699418036-fb5d179fef0c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1634&q=80" class="img-fluid z-depth-1-half" alt="">

      </div>
    </div>
  </div>

  <hr class="my-5">

  <!-- Container (Services Section) -->
<div class="valeurs">
  <div id="services" class="container-fluid text-center">
    <h1>Nous rejoindre</h1>
    <h4>Envoi nous un mail et nous nous ferons un plaisir de te contacter</h4>
  <br><button style="margin-top: 20px; argin-bottom: 20px;" class="btn btn-success btn-lg">Nous contacter</button>
</div>
</div>
</div>

app/views/pages/howitworks.erb
<div class="container text-center">
  <div class="cadre">
    <h2>Comment ca marche ?</h2>
    <h4>Facile et ludique</h4>


    <div class="row text-center">
      <div class="col-sm-4">
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1527731086039-8e31150599cf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTJ8fHN1cmZpbmd8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60);">
        <div class="thumbnail">
            <h3><strong>Note les spots</strong></h3>
            <p>Indique la meilleure marée, le meilleur vent, la meilleure houle</p>
        </div>
      </div>
    </div>
      <div class="col-sm-4">
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1513569143478-b38b2c0ef97f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTd8fHN1cmZpbmd8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60)" style=" transition: box-shadow 0.5s;";">
        <div class="thumbnail">
            <h3><strong>Mémo</strong></h3>
            <p>Visualise tous les spots sur la map. Mofifie les à tout moment. Partage les à tes potes</p>
        </div>
      </div>
    </div>
      <div class="col-sm-4">
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1612025344470-df9818c785a4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjh8fHN1cmZpbmd8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60);">
        <div class="thumbnail">
            <h3><strong>Météo</strong></h3>
            <p>Découvre les conditions météo de tes spots. </p>
        </div>
      </div>
    </div>
</div>

<%#-----------------------------fin card--------------------------------------------- %>
<hr class="my-5">

<div class="container-fluid">
  <div class="cadre2">
    <div class="text-center">
      <h2>3 étapes simples</h2>
      <h4>Marques tes spots et retrouve les meilleurs conditions et leurs météos</h4>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="panel panel-default text-center">
          <div class="panel-heading">
            <h1>Marque tes spots</h1>
          </div>
          <div class="panel-body">
            <p><strong>20</strong> Lorem</p>
            <p><strong>15</strong> Ipsum</p>
            <p><strong>5</strong> Dolor</p>
            <p><strong>2</strong> Sit</p>
            <p><strong>Endless</strong> Amet</p>
          </div>
          <div class="panel-footer">
            <h3>$19</h3>
            <h4>per month</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="panel panel-default text-center">
          <div class="panel-heading">
            <h1>Retrouve leurs infos</h1>
          </div>
          <div class="panel-body">
            <p><strong>50</strong> Lorem</p>
            <p><strong>25</strong> Ipsum</p>
            <p><strong>10</strong> Dolor</p>
            <p><strong>5</strong> Sit</p>
            <p><strong>Endless</strong> Amet</p>
          </div>
          <div class="panel-footer">
            <h3>$29</h3>
            <h4>per month</h4>
          </div>
        </div>
      </div>
    <div class="col-sm-4">
        <div class="panel panel-default text-center">
          <div class="panel-heading">
            <h1>Découvre la météo surf de chaque spot </h1>
          </div>
          <div class="panel-body">
            <p><strong>100</strong> Lorem</p>
            <p><strong>50</strong> Ipsum</p>
            <p><strong>25</strong> Dolor</p>
            <p><strong>10</strong> Sit</p>
            <p><strong>Endless</strong> Amet</p>
          </div>
          <div class="panel-footer">
            <h3>$49</h3>
            <h4>per month</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_slidebar.html.erb
<%# ---------------------------/NAVBAR-------------------------------------------------- %>
<div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
         <div class="conten_nav">

            <div class="sidebar-header">
                <h3>Welcome to SessionsShare</h3>
            </div>


            <ul class="list-unstyled components">
                <p>Note tes spots et partage les à tes potes.</p>

            <li class="nav-item">
              <div class="nav-link">
                <div class="input-group-prepend">
                  <%= form_tag spots_path, method: :get do  %>
                    <%= text_field_tag :query,
                      params[:query],
                      class: "form-control",
                      placeholder: "Chercher un spot.." %>
                      <%= submit_tag "🔎", class: "input-group-text", style: "border-top-right-radius: 30px; border-bottom-right-radius: 30px;" %>
                      <% end %>
                      </div>
                    </div>
            </li>
                <li>
                    <a href="../spots.html" id="slide1">MES SPOTS</a>

                <li>
                <li>
                    <a href="../pages/howitworks.html" id="slide2">COMMENT CA MARCHE</a>

                <li>
                <li>
                    <a href="../pages/values.html" id="slide3">VALEURS ?</a>

                <li>
                    <%= link_to "DECONNEXION 🚀", destroy_user_session_path, method: :delete, id: "slide4" %></a>
                </li>
            </ul>



            <ul class="list-unstyled CTAs">
                <li>
                <a href="#" ><%= link_to "Ajouter un spot", new_spot_path, class:"download"  %></a>
                </li>
                <li>
                    <a href="https://www.lacanausurfinfo.com/page/previsions-surf-plage-37/meteo-surf-7-jours.html" class="article">Favoris</a>
                </li>
            </ul>
           </div>
        </nav>

        <!-- Page Content  -->
            <div id="content">

            <nav class="navbar navbar-expand-lg sticky-top" style="overflow: hidden;
">


                    <button type="button" id="sidebarCollapse" class="btn btn-info" onclick="closeNav()">
                        <i class="fas fa-align-left"></i>
                        <span></span>
                    </button>


                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ">
                            <li class="nav-item active">
                                <a class="nav-link" href="../spots.html" style="box-shadow: inset 0 -12px 0 #4d854b61;
  color: rgb(53, 102, 83);">SessionsShare</a>
                            </li>
<%# ---------------------------search bar---------------------------------------- %>

<%# ---------------------------/search bar---------------------------------------- %>
                        </ul>
                    </div>
                </div>
            </nav>
<%# ---------------------------/NAVBAR-------------------------------------------------- %>

app/views/spots/_info_window.html.erb
<h2><%= spot.name.capitalize %></h2>

<%= link_to 'Voir le spot', spot, class: "btn btn-primary" %>

app/views/spots/index.html.erb
<div class="container">
  <div class="modal-body row">

      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="colonne_droite ">
          <div id="map" style="width: 100%; min-height: 100vh; margin-top: 16px;" style="position:sticky"
            data-controller="mapbox"
            data-mapbox-markers-value="<%= @markers.to_json %>"
            data-mapbox-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>"></div>
        </div>
      </div>

    <div class="col-xs-12 col-sm-8 col-md-8">
        <div class="colonne_gauche">
<%#------------------------Carte vide-------------------------------------------  %>
          <div class="carte_vide">
          <%= link_to new_spot_path do %>
            <div class="card" style="width: 100%;" >
              <div class="card_image">
                  <img src="https://www.situaction.fr/wp-content/uploads/2017/08/add-icone.jpg" class="card-img-top">
              </div>
                  <div class="card_content">
                    <h5 class="card-title"><h2  style="font-size: 22px; min-height: 31px ;font-weight: 700; color: white;"><%= "Créer un Spot" %></h2> </h5>
                    <h4  style="font-size: 15px; text-transform: capitalize, min-height: 31px;"><%= "Pays" %> </h4>
                    <p class="card_text" style="margin-bottom: -45px;"><%= "Description du spot" %>...</p>
                      <div class="text-center">
                          <%= link_to 'Créer un spot', new_spot_path, class: "btn btn-outline-primary", style: "font-size: 12px; position: relative; top:20px; align-items: center; color: white; border: solid 2px white" %>
                      </div>
                      <% end %>
                  </div>
            </div>
          </div>
<%#------------------------fin Carte vide-------------------------------------------  %>



          <% @spots.each do |spot| %>
              <div class="card" style="width: 100%;">
            <%= link_to spot do %>
                <div class="card_image">
                  <% if spot.image.attached? %>
                    <%= image_tag spot.image %>
                  <% else %>
                    <img src="https://images.unsplash.com/photo-1526342122811-2a9c8512023d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fHN1cmZpbmd8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60" class="card-img-top">
                  <% end %>
                </div>
                    <div class="card_content">
                      <h5 class="card-title"><h2  style="font-size: 22px; min-height: 31px ;font-weight: 700; box-shadow: inset 0 -12px 0 #4d854b61; color: rgb(53, 102, 83);"><%= spot.name.capitalize %></h2> </h5>
                      <h4  style="font-size: 15px; text-transform: capitalize, min-height: 31px;"><%= spot.country%> </h4>
                      <p class="card_text"><%= spot.description.first(70) %>...</p>
                        <div class="text-center">
                            <% link_to 'Mettre à jour', edit_spot_path(@spots) %>
                            <%= link_to 'Voir le spot', spot, class: "btn btn-outline-primary", style: "font-size: 12px; position: relative; top:20px; align-items: center" %>
                            <% link_to 'Ajouter aux favoris', spot, class: "btn btn-outline-success" %>
                            <% link_to 'Supprimer', @spot, method: :delete, data: { confirm: 'Are you sure?' } %>
                        </div>
                    </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/spots/show.html.erb
<div class="container">
  <div class="modal-body row" style="margin-top: 20px; justify-content: center">
    <div class="show_title" style="display: flex; justify-content: space-between; align-content: stretch; align-items: stretch;">
      <div class="title_title">
        <h5 class="card-title" style="margin-bottom: 2px;"><%= @spot.name.capitalize %></h5>
        <div class="card_totale_text" style="display: flex;">
          <p class="card-text" style="margin-left: 20px; padding-top:0px; font-size: 14px;"> <div class="card-text1"> · <%= @spot.country%></div> <div class="card-text2"> ·  <%= @spot.note %> <i class="fa-solid fa-star" style="color: #e61e4e;"></i></div> <div class="card-text3"> · Crée le <%= @spot.created_at.to_formatted_s(:short)%></div> </p>
        </div>
      </div>

      <div class="title_btn">
          <div class="card-body" style="padding-top: 19px; padding-left: 10px; margin-bottom: 17px;padding-bottom: 5px;">
            <a class="card-link"> <%= link_to 'Modifier', edit_spot_path(@spot), class: 'btn btn-outline-success', style: "font-size: 14px;"  %> </a>
            <a class="card-link"><%= link_to 'Supprimer', @spot, method: :delete, data: { confirm: 'Etes vous sur?' }, class: 'btn btn-outline-primary', style: "font-size: 14px;" %> </a>
            <a class="card-link"><%= link_to 'Retour', spots_path, class: 'btn btn-outline-danger', style: "font-size: 14px;"  %></a>
          </div>
        </div>
    </div>

      <div class="col-xs-12 col-sm-6 col-md-7">
            <div class="card" style="width: 100%; border-radius: 30px; background-color: #f3f3f3; border: 0px">
                <div class="card-img-top">
                  <% if @spot.image.attached? %>
                  <%= image_tag @spot.image, style:"height: 300px; width: 100%; object-fit: cover; BORDER-TOP-LEFT-RADIUS: 30px; BORDER-BOTTOM-LEFT-RADIUS: 30px;" %>
                  <% else %>
                  <img src="https://images.unsplash.com/photo-1466094899371-97b327dff551?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTB8fHN1cmZpbmd8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60" style="width: 100%; height: 300px;" class="card-img-top">
                  <% end %>
                </div>

                <ul class="list-group list-group-flush" style="border-top-color: rgb(220, 220, 220);"></ul>
                <h5 class="card-adresse" style="margin-bottom: 2px; margin-top: 20px; margin-left: 10px;"><%= @spot.adresse %></h5>

                  <div class="card-body" style="padding-top: 0px; padding-left: 10px;">
                  <div class="ligne_grise"></div>
                    <p class="card-text" style="line-height: 24px; font-size: 14px; -webkit-line-clamp: 6; display: -webkit-box; -webkit-line-clamp: 6;-webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis;"> <%= @spot.description %> </p>
                  </div>
                  <div class="ligne_grise"></div>





<table>
  <tr>
    <td id="titre1"><strong>Taille</strong></td>
    <td id="titre1"><strong>Meilleure Marée</strong></td>
    <td id="titre1"><strong>Meilleur période</strong></td>
    <td id="titre1"><strong>Direction vent</strong></td>
    <td id="titre1"><strong>Direction houle</strong></td>
  </tr>
  <tr>
    <td><%= @spot.meilleure_taille %></td>
    <td><%= @spot.best_tide %></td>
    <td><%= @spot.periode %> s</td>
    <td>
                    <% if @spot.best_wind == "Sud-Est" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-SE.png" title="SE">
                     <% elsif @spot.best_wind == "Sud" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-S.png" title="S">
                     <% elsif @spot.best_wind == "Sud-Ouest" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-OSO.png" title="OSO">
                     <% elsif @spot.best_wind == "Ouest" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-O.png" title="O">
                     <% elsif @spot.best_wind == "Est" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-E.png" title="E">
                     <% elsif @spot.best_wind == "Nord-Est" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-NE.png" title="NE">
                     <% elsif @spot.best_wind == "Nord" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-N.png" title="N">
                     <% elsif @spot.best_wind == "Nord-Ouest" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-NO.png" title="O">
                     <% end %>
      <%= @spot.best_wind.capitalize %>
    </td>

    <td>
                     <% if @spot.houle == "Sud-Est" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-SE.png" title="SE">
                     <% elsif @spot.houle == "Sud" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-S.png" title="S">
                     <% elsif @spot.houle == "Sud-Ouest" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-OSO.png" title="OSO">
                     <% elsif @spot.houle == "Ouest" %>
                     <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-O.png" title="O">
                     <% elsif @spot.houle == "Est" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-E.png" title="E">
                     <% elsif @spot.houle == "Nord-Est" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-NE.png" title="NE">
                     <% elsif @spot.houle == "Nord" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-N.png" title="N">
                     <% elsif @spot.houle == "Nord-Ouest" %>
                      <img width="25" height="25" src="https://www.francesurfinfo.com/affiliation/images/previsions/direction-NO.png" title="O">
                     <% end %>
        <%= @spot.houle %>
    </td>
  </tr>


</table>
</div>

    </div>


          <div class="col-xs-12 col-sm-6 col-md-5">
            <div class="colonne_droite_show">
              <div id="map" style="width: 100%; height: 643px; margin-top: 13px; object-fit: cover; "
                data-controller="mapbox"
                data-mapbox-markers-value="<%= @markers.to_json %>"
                data-mapbox-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
              </div>

          </div>
  </div>
              <div class="partage_ami">
                <h3> <%= "Partager ce spot à un ami" %> </h3>
                <p> <%= "Facebook : www.sdniznfiaiaoizi.com" %> </p>
                <p> <%= "Messenger : www.sdniznfiaiaoizi.com" %> </p>
                <p> <%= "Lien : www.sdniznfiaiaoizi.com" %> </p>
              </div>
            </div>


 <div id="windy"></div>
        <script src="script.js"></script>

</div>